### ISSUE TITLE
subsvc tech test

### ISSUE THREAD

**Issue by lamebrain** [MicrosoftDocs/CSIDev-Public-PPE#25]
---
#### Document Details
* Service: **service**
* Sub-service: **subservice**
* Product: **product**
* Technology: **technology**

**Comment by adunndevster** [comment]
#pri1

**Comment by adunndevster** [comment]
#pri2

**Comment by adunndevster** [comment]
#backlog

**Comment by adunndevster** [comment]
#pri3

**Comment by adunndevster** [comment]
Wow. `It's so great that the toggles for  #pri1 and such are gone.`

**Comment by adunndevster** [comment]
`#pri1`

**Comment by adunndevster** [comment]
#pri1

**Comment by adunndevster** [comment]
#pri3

**Comment by adunndevster** [comment]
#assign @bharney-msft

**Comment by PRMerger14** [comment]
bharney-msft is not a valid GitHub ID, or is not a collaborator on this repo.

**Comment by meganbradley** [comment]
#backlog

**Comment by meganbradley** [comment]
#pri1

**Comment by meganbradley** [comment]
@adunndevster tried *#pri1* a little while ago and so far the label hasn’t changed.

**Comment by meganbradley** [comment]
@adunndevster nvm, when I recommenced it showed up. Maybe a difference in the refresh behavior when working on my phone. #pri3

**Comment by meganbradley** [comment]
Looks good except all the labels should be capitalized. Pri3 is but pri1 isn’t. How about #pri2?

**Comment by meganbradley** [comment]
pri2 also uncapitalized. Confirming #backlog does nothing...

**Comment by meganbradley** [comment]
#assign:tysonn

**Comment by PRMerger15** [comment]
#assign:tysonn is not a valid GitHub ID, or is not a collaborator on this repo.

**Comment by PRMerger15** [comment]
#assign:tysonn is not a valid GitHub ID, or is not a collaborator on this repo.

**Comment by PRMerger15** [comment]
#assign:tysonn is not a valid GitHub ID, or is not a collaborator on this repo.

**Comment by PRMerger15** [comment]
#assign:tysonn is not a valid GitHub ID, or is not a collaborator on this repo.

**Comment by PRMerger15** [comment]
#assign:tysonn is not a valid GitHub ID, or is not a collaborator on this repo.

**Comment by PRMerger15** [comment]
#assign:tysonn is not a valid GitHub ID, or is not a collaborator on this repo.

**Comment by PRMerger15** [comment]
#assign:tysonn is not a valid GitHub ID, or is not a collaborator on this repo.

**Comment by PRMerger15** [comment]
#assign:tysonn is not a valid GitHub ID, or is not a collaborator on this repo.

**Comment by PRMerger15** [comment]
#assign:tysonn is not a valid GitHub ID, or is not a collaborator on this repo.

**Comment by PRMerger15** [comment]
#assign:tysonn is not a valid GitHub ID, or is not a collaborator on this repo.

**Comment by PRMerger15** [comment]
#assign:tysonn is not a valid GitHub ID, or is not a collaborator on this repo.

**Comment by PRMerger15** [comment]
#assign:tysonn is not a valid GitHub ID, or is not a collaborator on this repo.

**Comment by PRMerger15** [comment]
#assign:tysonn is not a valid GitHub ID, or is not a collaborator on this repo.

**Comment by PRMerger15** [comment]
#assign:tysonn is not a valid GitHub ID, or is not a collaborator on this repo.

**Comment by PRMerger15** [comment]
#assign:tysonn is not a valid GitHub ID, or is not a collaborator on this repo.

**Comment by PRMerger15** [comment]
#assign:tysonn is not a valid GitHub ID, or is not a collaborator on this repo.

**Comment by PRMerger15** [comment]
#assign:tysonn is not a valid GitHub ID, or is not a collaborator on this repo.

**Comment by PRMerger15** [comment]
#assign:tysonn is not a valid GitHub ID, or is not a collaborator on this repo.

**Comment by PRMerger15** [comment]
#assign:tysonn is not a valid GitHub ID, or is not a collaborator on this repo.

**Comment by PRMerger15** [comment]
#assign:tysonn is not a valid GitHub ID, or is not a collaborator on this repo.

**Comment by PRMerger15** [comment]
#assign:tysonn is not a valid GitHub ID, or is not a collaborator on this repo.

**Comment by PRMerger15** [comment]
#assign:tysonn is not a valid GitHub ID, or is not a collaborator on this repo.

**Comment by PRMerger15** [comment]
#assign:tysonn is not a valid GitHub ID, or is not a collaborator on this repo.

**Comment by PRMerger15** [comment]
#assign:tysonn is not a valid GitHub ID, or is not a collaborator on this repo.

**Comment by PRMerger15** [comment]
#assign:tysonn is not a valid GitHub ID, or is not a collaborator on this repo.

**Comment by PRMerger15** [comment]
#assign:tysonn is not a valid GitHub ID, or is not a collaborator on this repo.

**Comment by PRMerger15** [comment]
#assign:tysonn is not a valid GitHub ID, or is not a collaborator on this repo.

**Comment by PRMerger15** [comment]
#assign:tysonn is not a valid GitHub ID, or is not a collaborator on this repo.

**Comment by PRMerger15** [comment]
#assign:tysonn is not a valid GitHub ID, or is not a collaborator on this repo.

**Comment by PRMerger15** [comment]
#assign:tysonn is not a valid GitHub ID, or is not a collaborator on this repo.

**Comment by PRMerger15** [comment]
#assign:tysonn is not a valid GitHub ID, or is not a collaborator on this repo.

**Comment by PRMerger15** [comment]
#assign:tysonn is not a valid GitHub ID, or is not a collaborator on this repo.

**Comment by PRMerger15** [comment]
#assign:tysonn is not a valid GitHub ID, or is not a collaborator on this repo.

**Comment by PRMerger15** [comment]
#assign:tysonn is not a valid GitHub ID, or is not a collaborator on this repo.

**Comment by PRMerger15** [comment]
#assign:tysonn is not a valid GitHub ID, or is not a collaborator on this repo.

**Comment by PRMerger15** [comment]
#assign:tysonn is not a valid GitHub ID, or is not a collaborator on this repo.

**Comment by PRMerger15** [comment]
#assign:tysonn is not a valid GitHub ID, or is not a collaborator on this repo.

**Comment by PRMerger15** [comment]
#assign:tysonn is not a valid GitHub ID, or is not a collaborator on this repo.

**Comment by PRMerger15** [comment]
#assign:tysonn is not a valid GitHub ID, or is not a collaborator on this repo.

**Comment by PRMerger15** [comment]
#assign:tysonn is not a valid GitHub ID, or is not a collaborator on this repo.

**Comment by PRMerger15** [comment]
#assign:tysonn is not a valid GitHub ID, or is not a collaborator on this repo.

**Comment by PRMerger15** [comment]
#assign:tysonn is not a valid GitHub ID, or is not a collaborator on this repo.

**Comment by PRMerger15** [comment]
#assign:tysonn is not a valid GitHub ID, or is not a collaborator on this repo.

**Comment by PRMerger15** [comment]
#assign:tysonn is not a valid GitHub ID, or is not a collaborator on this repo.

**Comment by PRMerger15** [comment]
#assign:tysonn is not a valid GitHub ID, or is not a collaborator on this repo.

**Comment by PRMerger15** [comment]
#assign:tysonn is not a valid GitHub ID, or is not a collaborator on this repo.

**Comment by PRMerger15** [comment]
#assign:tysonn is not a valid GitHub ID, or is not a collaborator on this repo.

**Comment by PRMerger15** [comment]
#assign:tysonn is not a valid GitHub ID, or is not a collaborator on this repo.

**Comment by PRMerger15** [comment]
#assign:tysonn is not a valid GitHub ID, or is not a collaborator on this repo.

**Comment by PRMerger15** [comment]
#assign:tysonn is not a valid GitHub ID, or is not a collaborator on this repo.

**Comment by PRMerger15** [comment]
#assign:tysonn is not a valid GitHub ID, or is not a collaborator on this repo.

**Comment by PRMerger15** [comment]
#assign:tysonn is not a valid GitHub ID, or is not a collaborator on this repo.

**Comment by PRMerger15** [comment]
#assign:tysonn is not a valid GitHub ID, or is not a collaborator on this repo.

**Comment by PRMerger15** [comment]
#assign:tysonn is not a valid GitHub ID, or is not a collaborator on this repo.

**Comment by PRMerger15** [comment]
#assign:tysonn is not a valid GitHub ID, or is not a collaborator on this repo.

**Comment by PRMerger15** [comment]
#assign:tysonn is not a valid GitHub ID, or is not a collaborator on this repo.

**Comment by PRMerger15** [comment]
#assign:tysonn is not a valid GitHub ID, or is not a collaborator on this repo.

**Comment by PRMerger15** [comment]
#assign:tysonn is not a valid GitHub ID, or is not a collaborator on this repo.

**Comment by PRMerger15** [comment]
#assign:tysonn is not a valid GitHub ID, or is not a collaborator on this repo.

**Comment by PRMerger15** [comment]
#assign:tysonn is not a valid GitHub ID, or is not a collaborator on this repo.

**Comment by PRMerger15** [comment]
#assign:tysonn is not a valid GitHub ID, or is not a collaborator on this repo.

**Comment by PRMerger15** [comment]
#assign:tysonn is not a valid GitHub ID, or is not a collaborator on this repo.

**Comment by PRMerger15** [comment]
#assign:tysonn is not a valid GitHub ID, or is not a collaborator on this repo.

**Comment by PRMerger15** [comment]
#assign:tysonn is not a valid GitHub ID, or is not a collaborator on this repo.

**Comment by PRMerger15** [comment]
#assign:tysonn is not a valid GitHub ID, or is not a collaborator on this repo.

**Comment by meganbradley** [comment]
#reassign:meganbradley weird loop happened when I tried to assign Tyson

**Comment by PRMerger16** [comment]
weird is not a valid GitHub ID, or is not a collaborator on this repo.

**Comment by PRMerger16** [comment]
weird is not a valid GitHub ID, or is not a collaborator on this repo.

**Comment by adunndevster** [comment]
#please-close
